# do not touch this line
configVersion: 2

description: Iot App
keywords: ''
name: raspbutin
shortName: raspbutin
displayName: Raspbutin

config:
  wakeword:
    wake_word: MATRIX
    channel: 0
    lm_path: 7365.lm
    dic_path: 7365.dic

services:
  faceDemo:
    engine: detection
    type: face
  voiceDemo:
    wakeword: matrix
    engine: voice
    phrases:
      - i'm hungry
      - get to aloha
      - aloha cafe
      - where is there to eat nearby
      - where can i get a quick bite
      -
