# do not touch this line
configVersion: 2

description: Iot App
keywords: ''
name: raspbutin
shortName: raspbutin
displayName: Raspbutin

events:
  - globalEvent

services:
  faceDemo:
    engine: detection
    type: face
  voiceDemo:
    wakeword: matrix
    engine: voice
    phrases:
      - find food
      - i am hungry
      - get to aloha
      - aloha cafe
      - where is there to eat nearby
      - where can i get a quick bite
      - shine blue
      - shine orange
      - beep
      - am hungry
      - where can i get some food
